[package]
name = "regression-analysis"
version = "0.1.0"
authors = ["Gear Technologies"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
clap = { version = "3.2", features = ["derive"] }
<<<<<<< HEAD
<<<<<<< HEAD
quick-xml = { version = "0.25", features = [ "serialize" ] }
tabled = "0.9.0"
junit-common = { path = "../junit-common" }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
=======
quick-xml = { version = "0.24", features = [ "serialize" ] }
=======
quick-xml = { version = "0.25", features = [ "serialize" ] }
>>>>>>> e9a8cde0 (merge master to vara (#1473))
tabled = "0.8.0"
junit-common = { path = "../junit-common" }
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.85"
>>>>>>> 4ff7e31a (Vara: Update stage 1 to latest master (#1464))
thousands = "0.2.0"

gear-runtime = { path = "../../runtime/gear" }
pallet-gear = { path = "../../pallets/gear" }
frame-support = { version = "4.0.0-dev", git = "https://github.com/gear-tech/substrate.git", branch = "gear-stable" }
