[package]
name = "gear-common-codegen"
version = "0.1.0"
authors = ["Gear Technologies"]
edition = "2021"
license = "GPL-3.0"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.21"
<<<<<<< HEAD
syn = "1.0.102"
=======
syn = "1.0.100"
>>>>>>> 1a441afd (Vara: merge master (#1529))
