[package]
name = "wasm-proc"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = { version = "3.2", features = ["derive"] }
log = "0.4.17"
<<<<<<< HEAD
<<<<<<< HEAD
env_logger = "0.9.1"
thiserror = "1.0.37"
=======
env_logger = "0.9.0"
thiserror = "1.0.34"
>>>>>>> 4ff7e31a (Vara: Update stage 1 to latest master (#1464))
=======
env_logger = "0.9.1"
<<<<<<< HEAD
thiserror = "1.0.35"
>>>>>>> 1a441afd (Vara: merge master (#1529))
=======
thiserror = "1.0.37"
>>>>>>> 4ca47efe (Merge branch 'master' into vara-stage-1)
gear-wasm-builder = { path = "../wasm-builder" }
parity-wasm = "0.45.0"
