[package]
name = "wasm-proc"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = { version = "3.2", features = ["derive"] }
log = "0.4.17"
<<<<<<< HEAD
env_logger = "0.9.1"
thiserror = "1.0.37"
=======
env_logger = "0.9.0"
thiserror = "1.0.34"
>>>>>>> 4ff7e31a (Vara: Update stage 1 to latest master (#1464))
gear-wasm-builder = { path = "../wasm-builder" }
parity-wasm = "0.45.0"
