[package]
name = "light_sr25519"
version = "0.1.0"
authors = ["Gear Technologies"]
edition = "2018"

<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 4ca47efe (Merge branch 'master' into vara-stage-1)
[dependencies.schnorrkel]
version = "0.10.2"
features = [
    "preaudit_deprecated",
    "u64_backend",
]
default-features = false
<<<<<<< HEAD
=======
[dependencies]
schnorrkel = { version = "0.9.1", features = [
	"preaudit_deprecated",
	"u64_backend",
], default-features = false }
>>>>>>> 4ff7e31a (Vara: Update stage 1 to latest master (#1464))
=======
>>>>>>> 4ca47efe (Merge branch 'master' into vara-stage-1)
