name: Purge cache

on: workflow_dispatch

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up
        run: |
          sudo ls -la /root/cache
          sudo rm -rvf /root/cache/*
