name: Restore DB backup

on:
  workflow_dispatch:
    inputs:
      backup_type:
        description: 'Restore type'
        required: true
        default: 'full'
        type: choice
        options:
        - full
        - increment
      increment_name:
        description: 'Increment backup name'
        required: false
        type: string
      gear02:
        description: 'Restore on testnet-gear02'
        required: false
        default: false
        type: boolean
      archive:
        description: 'Restore on testnet-archive'
        required: false
        default: false
        type: boolean

env:
  DB_PATH: /home/ec2-user/gear-data/chains/gear_staging_testnet_v4

jobs:
  restore-backup-on-gear02:
    if: ${{ inputs.gear02 }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Send telegram notify before create backup
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ✅ Restore DB was successfully completed on testnet-gear02

      - name: Restore backup
        uses: dawidd6/action-ansible-playbook@v2
        with:
          directory: ./ansible/
          playbook: testnet-restore.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
            ${{ inputs.restore_on.gear02 }} ${{secrets.GEAR_NODE_2}} build_number=${{ github.run_number }} db_path=${{ env.DB_PATH }} restore_type=${{ inputs.backup_type }} increment_backup_name=${{ inputs.increment_name }}

      - name: Send telegram notify after create backup
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ✅ Restore DB was successfully completed on testnet-gear02

  restore-backup-on-archive:
    if: ${{ inputs.archive }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Send telegram notify before create backup
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🔥 Start restore DB on testnet-archive

      - name: Restore backup
        uses: dawidd6/action-ansible-playbook@v2
        with:
          directory: ./ansible/
          playbook: testnet-restore.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
            ${{ inputs.restore_on.archive }} ${{secrets.ARCHIVE_NODE}} build_number=${{ github.run_number }} db_path=${{ env.DB_PATH }} restore_type=${{ inputs.backup_type }} increment_backup_name=${{ inputs.increment_name }}

      - name: Send telegram notify after create backup
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ✅ Restore DB was successfully completed on testnet-archive
